#!/bin/bash
# Note: First you must run mvn dependency:build-classpath -Dmdep.outputFile=script/maven-classpath 
CLASSPATH=src/main/clojure:src/test/clojure:src/examples/clojure:`cat script/maven-classpath`

USER_SCRIPT=$1
shift
if [ "$USER_SCRIPT" != "" ]; then
    USER_SCRIPT="-i $USER_SCRIPT -r "
fi

java -server -Xmx2GB -cp $CLASSPATH clojure.main $USER_SCRIPT


